server:
  port: 8082

spring:
  application:
    name: hotel-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_service}
    username: ${SPRING_DATASOURCE_USERNAME:user_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:user_db_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect